### ISSUE TITLE
Autocompletion doesn't works

### ISSUE THREAD

**Issue by Calystod** [FloeDesignTechnologies/ansible-nginx-drupal#18]
After a security issue on Drupal core https://www.drupal.org/SA-CORE-2015-003, the autocomplete has been changed.

Relative to this issue https://www.drupal.org/node/2599326#comment-10850594, I added a new rule on drupal.j2

**Comment by Calystod** [comment]
See #19

**Comment by mathieuhelie** [comment]
Merged #19
